### ISSUE TITLE
Allow array view components?

### ISSUE THREAD

**Issue by thequailman** [jorgebucaran/hyperapp#1002]
Given a component like this (no state for simplicity):

```
export const someText = () => {
	return [
		h("p", {}, text("a)),
		h("p", {}, text("b))
	];
}
```

You can't seem to consume it in other components:

```
export const test = () => {
	return someText()
}

Uncaught TypeError: Cannot read property 'is' of undefined
```

Not sure if I'm doing something wrong or this might be expected behavior.  I think I can work around that, but there are some types of components that would be best to return as an array.

**Comment by zaceno** [comment]
You should definitely be able to consume that in another component. The thing is you have to make sure that the top-level view is just a single node. Not an array.

**Comment by zaceno** [comment]
With your examples, you should be able to do:

```js
app({
   view: state => h('div', {}, test())
})
```

and get the resulting:

```html
<div>
  <p>a</p>
  <p>b</p>
</div>
```

**Comment by zaceno** [comment]
Or hang on - maybe I don't understand your question. Your first example was `someText`, but then you consume `input`. What is `input`?

**Comment by thequailman** [comment]
My bad, I had changed the example, I'm making a flems to demo

**Comment by thequailman** [comment]
See this, I think: https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgCNaATATwD4AdNAAIhLLBgjCInALz8QGAA6L5vFgHpxkgWg0cevSiDgxY1YhHoJEIAIyJbAdhABfCumy4b+AFYIqdAxMxHgQWIq0AE7EQsBKihRChImMAB7ELkJgkbRYQvKE3IowkfHygoKBcDFwuTAAKjDpQjJCABQAlC28sYIikTDEAK6Rwsh9Iklt8iqUsW5CacTTIGzyHR0UEyKEK7OJwAtLK9TrmxMAugDcgi43aJVWNXUAahAwAO4t7V0yPcATAbDUZTeScCAAN3kBwW42Ek12M2h8xSTWW8gwZy28JEtRwjXSnWxIguHVuFUwyjaAPhkggxEQKImEPeH0ZnW6vRxQiBI2EiJA4Khc0OiTxMDen06HXuIjcEzQXBgjM4tGoQxwDHwAHNBgBRWCa4gAIW4AElOCsyiBzmgXB0jHRwtASng2Bg2KYjCYzBYrHhbAAWByudwgTA4PD4ahwfw0eiMZg2VwXKhQSQAa2sqHDnjwhWKpWURhG5BsJGIijgiHU6iGaEUGe10dy6gLJXiAAEAEz4AAM+AAHG2ih3lL448RR3g4NRIhBFCEXBcXEA

**Comment by thequailman** [comment]
I think it's because of what you said, you can't use an array inside of an array?

**Comment by zaceno** [comment]
Ah, yeah: hyperapp doesn't expect you to nest arrays. 
try
```js
...someText(),
```
😉

**Comment by thequailman** [comment]
Excellent!  Thank you

**Comment by zaceno** [comment]
@thequailman By the way, just in case it's interesting to you (but since you're coming from mithril I'm guessing not very): Hyperlit takes care of array-flattening children so your example could look like this: 

https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgCNaATATwD4AdNAAIhLLBgjCInALz8QGAA6L5vFgHpxkgWg0cevSiDgxY1YhHoJEIAIyJbAdhABfCumy4b+AFYIqdAxMxHgQWIq0AE7EQsBKii5CYJG0WELyhNyKMJHx8oJhEdFCJGRJKWkA5CTEinCI6uoArmiKANYA5vh0WOqZ2ZFQEMSVgoKBcDFwqTAAKjAAHjEyQgAUAJRCMrwlpFAABoIiLIq8bBqnR6Kn1Be8h2jjVlMzAGoQMADuW2ub27tkB7HTgQABuOhEx1OGDuVxEABJgNMcPMlhsXFcNCDwQ9BPFVsArpJhohYm4rqCPp9SRstjtSgcWNjeIjkTB3l90ViwfcKFc0FwYKTOLRqE0cAx8B0YMQAKKwCXEABC3AAkpxVvI8iB1ny0C51kYeopoDk8GwMGxTEYTGYLFY8AAGBy2VzuECYHB4bpwfw0eiMZg2VwAXSoQzQbWsqA9njw-Ry8SMTUG8eItXqjRa7S6PT6WUTygAAgAmfCO-AADnzA3ivj9xALeDg1EiEEUIRcIZcQA
