### ISSUE TITLE
using init() and an action

### ISSUE THREAD

**Issue by Seanmcdon** [jorgebucaran/hyperapp#1057]
when I use init, I have a problem accessing the state in the action. this is my code:

`
  app({ init: () => [  { data: ":some data" },
                                transferData({onresponse: getDataComplete, url: "json.php", data: { func: "get-data" }}) 
                            ],
      node: document.getElementById("hyperapp"),
      view: state => container(state)  
   });

`
now in transferData, how do I access and setup the state? 

`const transferData = (payload) => {
  
    fetch('json.php', {
      method: 'POST', // or 'PUT'
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload.data),
    })
    .then(response => response.json())
    .then(data => {

      console.log(data);
      return data;
      
      //requestAnimationFrame(() => dispatch(payload.action, data));
      
    })
    .catch((error) => {
      console.error('Error:', error);
    });

}`

I haven't found documentation on this specifically. For some reason, my 'action' function, (transferData), does not have 'state' as it's first argument. 

I would be willing to work on documentation for this kind of practical application.

**Comment by Seanmcdon** [comment]
Ok, so I'm getting somewhere using the fx package Http().

Now, the problem is that my action() function relays to another function, which is not updating the state....

It does not seem easy to implement a fetch() or http() on ones own. If I'm correct, you have to somehow get hyperapp to 'act' with the fetch response. Http() must implement this.

**Comment by zaceno** [comment]
Sorry, I know it doesn't _seem_ easy to implement a http() effect on your own.  Believe me I get it! It took me quite some wrapping my head around. But please take this on faith: it is actually way easier than it seems. Once it clicks it makes a lot of sense.

That's why I wrote that article I linked to in your other issue. I'm trying to find a good progression for making the effects-idea click with folks. In case you didn't read it before, maybe give it a shot? (https://gist.github.com/zaceno/36fefb3acccd895f371a66357ad293df) – I think it will help  but if it doesn't, please let me know at what point I lost you.

There is also a video here: https://zaceno.github.io/codealong-hyperapp/#n10 (number 10) where I explain effects in a similar way, in case videos are more your thing.

In any case, your init (such as I understand what you're going for) could all be written inline in one blob of nested code like this:

```js
app({
  init:  () => [
    {data: ':some data'},
    [dispatch => {  // <-- notice the `dispatch` here. Hyperapp calls your effect runner with it as argument
    
      fetch('./json.php', {
        method: 'POST',  
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({func: "get-data"})
      })
      .then(response => response.json())
      .then(data => {
        console.log('GOT DATA: ', data)
        // here we use the `dispatch` function hyperapp provides
        // to "call back" an action with the response data:
        dispatch(getDataComplete, data)
      })
    }]
  ],
  node: document.getElementById("hyperapp"),
  view: state => container(state)
});
```

The above assumes that `getDataComplete` is in scope and defined as an _action_, i e a state-transformation function. So something like this presumably:

```js
const getDataComplete = (state, data) => ({...state, data})
```

Anyway, of course you wouldn't want to have all the code in line like that.  It's hard to read, and what's worse: impossible to reuse. Here's how I would split it up:

```js

// -- this is the reusable, generic effect definition

const _postAndGetJSON = (dispatch, options) => {
  fetch(options.url, {
    method: 'POST',  
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(options.body)
  })
  .then(response => response.json())
  .then(data => {
    dispatch(options.action, data)
  })
 }

const postAndGetJSON = (url, body, action) => [
  _postAndGetJSON,
  {url, body, action}
]

// --- This is the app specific code: 

const getDataComplete = (state, data) => ({...state, data})

app({
  init:  () => [
    {data: ':some data'},
    postAndGetJSON(
       './json.php',
       {func: 'get-data'},
       getDataComplete
    )
  ],
  node: document.getElementById("hyperapp"),
  view: state => container(state)
});
```

Hope that helps!

**Comment by Seanmcdon** [comment]
Wow, thanks a lot!

I did take a look at your article. I will go back and see where I felt like I couldn’t put this into use at the init(). 

I’ll let you know!

**Comment by Seanmcdon** [comment]
I'm sorry but there is still something going on wrong here. 

As your code shows, in the callback function of fetch(), I dispatch the action() and it returns a new state. The new state is correctly set now. 

However, the view has already rendered. And the new data is not updated into the view....
