### ISSUE TITLE
Memo Data Gotcha

### ISSUE THREAD

**Issue by kofifus** [jorgebucaran/hyperapp#1080]
I am confused about the "Memo Data Gotcha" example in https://github.com/jorgebucaran/hyperapp/blob/main/docs/api/memo.md#memo-data-gotcha

What exactly is the gotcha here ? why wouldn't the action cause the memoized view to rerender ?
Perhaps this can be made clearer in the doc.

Thanks!

**Comment by zaceno** [comment]
The problem is that the value of  `state.list` will alternate between e.g.:  `['a', 'b', 'c']` and `"abc"` 

They way hyperapp compares the previous memo-value to the current one is using a for-in loop and the problem is:

```js
const old = 'abc'
const current = ['a','b','c']
let same = true //old and current assumed the same until proven otherwise

for (key in old) {
  if (old[key] !== current[key]) {
    //doesn't actually happen because old[1] => 'b' and current[1]=>'b' et c
    same = false
  }
} 
```

While this is very much an edge case (so much so that I question wether it's worth including in the docs at all) I think the explanation is pretty ok

> So, any indexable type like strings and arrays can be compared with one another and in certain edge cases be considered "equal" 

... at least I don't know how to improve on it but feel free to contribute! 🙂

**Comment by kofifus** [comment]
Thanks ! perhaps in the example we can change `randomHex()` to `randomChar()` and then after 
> So, any indexable type like strings and arrays can be compared with one another and in certain edge cases be considered "equal" when it comes to determining if a re-render should happen.

We can add
> (ie ['a','b','c'] vs 'abc')

Does that makes sense ?

Another relevant question (perhaps belonging in a separate thread), is the general experience that the majority of real world cases are better with `memo` or without it ? would it be helpful to have an option to `memo` by default ?

**Comment by zaceno** [comment]
Those are good suggestions. I’ve been considering a docs PR to fix another issue I’ve seen so I’ll make sure to include these ther if/when I do.

about the memo by default thing I think it’s a good question and I’m not really sure. To be honest I think for most realistic scenarios it doesn’t matter at all wether you do or don’t. 

But it would be pretty interesting to study and find out exactly how much it helps when, for sure.

**Comment by kofifus** [comment]
Also considering your code above comparing old and current, is there a reason why there is no check for type equality first ? (`typeof x === typeof y` or something more fancy) maybe something like that can prevent the gotcha completely ?

**Comment by zaceno** [comment]
@kofifus I suppose the reason it's _not_ done that way is we're trading some perfect-cover-all-bases-ness for brevity. That philosophy is why hyperapp can be so lightweight. 

I think the tradeoff is totally fair since neither strings or arrays are really "normal" usage in memo – I don't see any realistic scenario where you would do that. Practically always you will memoize on objects with props (in which case there are no gotchas). I feel like the docs could probably emphasize that more.
