### ISSUE TITLE
Actions returning other Actions

### ISSUE THREAD

**Issue by kofifus** [jorgebucaran/hyperapp#1089]
I wanted to ask/comment about the Action "overloads" that are self referencing:
`Action: someAction` and `Action: [ somneAction, payload ]`

This was one of the things I found most confusing when learning hyperapp.

I don't fully understand the usage for it and as far as the overall architecture it somehow feels like a kludge ... Why have an action `s => [otherAction, payload]` when we can do `s => otherAction(s, payload)` which is simpler and doesn't involve dispatching ? or am I missing the obvious ?

Is this by design or is this just a side effect of the way hyperapp is coded that then felt like a 'bonus' (dispatch recursively calling itself with elements of the array  from `[newState, ...effects]` [here](https://github.com/jorgebucaran/hyperapp/blob/main/index.js#L412) ?

What if we disallow/discourage `state => Action` and `state => [Action, payload ]` and achieving that will have to be by direct calls as above or go through effects ? (`runAction` / `runInNextFrame` etc) ? wouldn't that be a better design in the sense that Action always leads to a new state optionally with effects ?

Any thoughts or opinions welcomed 🙂

**Comment by kofifus** [comment]
thanks @zaceno !

considering the last snippet wouldn't it be better to do:
```
oninput: (state, event) => SetInput(state, {str: event.target.value, index})
```

wouldn't be exactly the same just clearer, more efficient (no extra dispatch), and removes the need for the Action returning [Action, payload] ?

**Comment by zaceno** [comment]
@kofifus Yes correct - by using a `dispatch: ` property in our app call we can hook in to dispatch for a variety of purposes. For example we could have a redux-dev-tools-style time-travelling debugger (such as @mrozbarry is working on), or we could have test-spies that verify that certain actions get dispatched from certain interactions or as a result of inputs et c (such as I plan to work on). 

Those examples would only be possible because 

```js
oninput: (state, event) => [SetInput, {str: event.target.value, index}]
```

works as a feature of Hyperapp.

Now of course what you wrote there works fine too and if you prefer it then go ahead and use it. As to which form should be encouraged... well people feel differently about that but going with your form means if you ever did want to use a debugger/test-utility you would have to refactor your actions. AFAIK that is why the current form is the recommended one.

**Comment by zaceno** [comment]
Another form that would work – and yet remain traceable, is (as you were alluding to)

```js
oninput: (state, event) => [state, d => d(SetInput, {str: event.target.value, index})]
```

Honestly I don't prefer it but 🤷 

Also, since we're on the topic of actions returning other actions, it means actions can be like a kind of "router" for other actions based on the current state/payload. For example this:

```js
const KeyPressed = (state, key) => 
     key ===  'ArrowUp' ? MoveUp
  :  key === 'ArrowDown' ? MoveDown
  :  key === 'Space' ? Shoot
  : state
```

With an action like that, it becomes possible to trace the logic `KeyPressed` –> `MoveDown` in a debugger, and distinguish that from for example `TimeStep` -> `MoveDown`

**Comment by kofifus** [comment]
Thanks @zaceno that is very helpful!
