### ISSUE TITLE
Has 2.0 been dropped from development?

### ISSUE THREAD

**Issue by ClearedFram3** [jorgebucaran/hyperapp#1104]
2.0 was talked about as if it was done for some time and a nice website was even released and pulled back too. What happened? Can I help in some way?

**Comment by jorgebucaran** [comment]
Current version is [2.0.22](https://github.com/jorgebucaran/hyperapp/releases/tag/2.0.22), I just haven't added release notes or being very public about it.

I also got a bit stuck with @hyperapp/http and @hyperapp/random. In order to implement them, we need to introduce a new helper package like Elm's task.

**Comment by tbreuss** [comment]
A little confusing here is the 2.0.0 release at https://github.com/jorgebucaran/hyperapp/releases, which is marked as prev-release, besides the tags at https://github.com/jorgebucaran/hyperapp/tags that are >= 2.0.22.

**Comment by jorgebucaran** [comment]
Agreed. I removed the pre-release tag.
