### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by foways** [jorgebucaran/hyperapp#694]
### Hello !

I am a designer and I am proficient in designing a logo, for this project I am applying a logo renewal. This is just a suggestion.

![hyperapp logo](https://user-images.githubusercontent.com/38687140/40445819-776da86e-5ef7-11e8-8fb7-39c16a5fb7d5.png)

**Comment by jorgebucaran** [comment]
@k-syusteem This logo is so cute. And it also has the 70s / 80s disco vibe I like.

**Comment by mrozbarry** [comment]
Now I have to make more shirts 😱

**Comment by jorgebucaran** [comment]
Maybe we can use this thread to propose more logo ideas!

**Comment by k-syusteem** [comment]
And I order 1 T-shirt from you @mrozbarry :100: 

Hi @jorgebucaran Are there any other suggestions on logo concept for this project?

**Comment by jorgebucaran** [comment]
@k-syusteem Not at the moment, but hopefully there will be. So, why did you want to change the logo? Could you point out how this new logo is better from a designer's perspective?

**Comment by k-syusteem** [comment]
Hi @jorgebucaran I will explain it through the visual image below:

![old](https://user-images.githubusercontent.com/38687140/40557238-b2c1e6ae-6079-11e8-8d52-4dd3990075ad.png)

![new2](https://user-images.githubusercontent.com/38687140/40557546-add2d29c-607a-11e8-8c2a-ec016eaa5e44.png)

![new](https://user-images.githubusercontent.com/38687140/40557287-d938a278-6079-11e8-8d7e-cdf15e300f17.png)

<b><i>I think people will get to know this logo better than "Hyper App"</i></b>

**Comment by jorgebucaran** [comment]
@k-syusteem Thanks, for the visual explanation, it makes sense. But could we see variations of this logo?

**Comment by atomiks** [comment]
Some thoughts.

- Logos should be relatively simple and look good at a very small size

- Simple shapes are most recognisable and iconic (Apple's apple, React's atom, Facebook's text or F, Google's text or G)

- An icon + `hyperapp` text is usually a good combo for a logo, as the icon can be used independently at times

- Hyperapp's core values are a functional programming approach to building apps + functional purity but with a pragmatic approach to side effects

- "Purity" is represented by a diamond or a droplet usually

![img](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fassets.digitalocean.com%2Fghost%2F2017%2F06%2FHigh-CPU-Droplets_blog.png)

- A unique take on a droplet could be possible rather than just making some abstract shapes from the letters `h` and `a`. The green thing in the center could mean it's containimated with side effects but still mostly pure. 🤣

**Comment by k-syusteem** [comment]
Exceptionally @atomiks, I really enjoy the inputs rather than you. @jorgebucaran Can! and I can give you some other variations!

**Comment by k-syusteem** [comment]
Hi @jorgebucaran! Following these are some new variations, and I also designed some versions as suggested by @atomiks.

![001](https://user-images.githubusercontent.com/38687140/40582585-0d4dcc74-61a5-11e8-908a-6e3a1b5483fe.jpg)
![0001](https://user-images.githubusercontent.com/38687140/40582734-e0e309c0-61a8-11e8-9a6e-04ea553f417d.jpg)
![0002](https://user-images.githubusercontent.com/38687140/40582735-e132f390-61a8-11e8-8720-ae56359da31d.jpg)
![0003](https://user-images.githubusercontent.com/38687140/40582736-e1a81648-61a8-11e8-9023-35658923892c.jpg)

**Comment by jorgebucaran** [comment]
@k-syusteem Wow, but what talent. Incredible work! 👏  

The abstract one (4) is pretty cool.

Could we keep trying? What do other people think? Hmm, I think we could also experiment with the original logo idea which was nothing else but a [hypercube](https://en.wikipedia.org/wiki/Hypercube). One more thing, the idea that the logo must stand as an ideogram of an `h` and `a` is not set in stone either.

As for the hypercube, something like this? 🤔 

![9e24935b341c60e4f0fa589823edd15a](https://user-images.githubusercontent.com/56996/40587418-b8f658a2-6209-11e8-953e-0c56025348fe.jpg)

**Comment by TacoTheDank** [comment]
h y p e r c u b e

**Comment by bboydflo** [comment]
number 4 looks super clean. IMO it is much more appealing to the eye than the rough edges of the hypercube

**Comment by k-syusteem** [comment]
![1](https://user-images.githubusercontent.com/38687140/40591410-1e398474-623b-11e8-8fb3-07f455377ffb.jpg)

#### Hi @jorgebucaran!

This is a cube version like your hint "hypercube". What is your opinion?

![2](https://user-images.githubusercontent.com/38687140/40591411-1e98e82e-623b-11e8-970f-b89190f1a3d3.jpg)
![3](https://user-images.githubusercontent.com/38687140/40591413-1f1f3370-623b-11e8-9f2e-2840215241b6.jpg)

### Information

![detail information](https://user-images.githubusercontent.com/38687140/40591483-63986782-623c-11e8-8351-15641942cbb2.jpg)

**Comment by TacoTheDank** [comment]
i don't think anyone would be able to tell that's an "a" lmao

**Comment by jorgebucaran** [comment]
We don't need an ideogram. It could very well be a common symbol, just like React uses a simplified atom symbol. One thing no one has mentioned in this thread is how heavily Hyperapp is based on Elm. Just adding ideas.

@k-syusteem That hexagon looks from outta space! You are awesome.

**Comment by okwolf** [comment]
I think for Hyperapp it makes more sense for the logo to have angular (not the Google kind) edges instead of smooth curves. Feels more like cutting-edge technology and less like a trendy brand of clothing.

**Comment by jorgebucaran** [comment]
I wish we had a logo that looked kinda like NASA, but I know that wouldn't really work haha.

**Comment by Swizz** [comment]
We should list some keywords around Hyperap to found the matching shape.
Lets start with the words given in this issue : 
Functionnal, purity, ease, ligthweight, cutting-edge, Elm.

To be honest, since you (@jorgebucaran) showed it to us, I am pretty in love about the Dynamicron logotype
[Special mention to use of the same called Sony Dynamicron VHS color palette](http://cdn1.goughlui.com/wp-content/uploads/2014/02/Sony-Dynamicron-Old-E180.jpg)
![Dynamicron Logo](https://pbs.twimg.com/profile_images/979405254612545536/WAec09mn_200x200.jpg) 

We need something this easy shapes like this.

So let's talk about pixels.  Pixels are the smalest units  : 1x1 (1KB). They are simple, and somehow pure (and idempotent most of the time) [(R, G, B) => color]. They are easy to reason about, one pixel have one and only one state. But they are powerfull because Pixels can be composed all together to make something incredible (Art, beauty, science, product). Also, if only one pixel is mutated, a brand new image is resulted (immutability).

So I would love to see a shape in a pixel art style.

**Comment by jorgebucaran** [comment]
Oh, _Dynamicron_, I love it too.

**Comment by jorgebucaran** [comment]
@k-syusteem Would it be possible to only tweak the current logo a bit, or perhaps reuse some of the ideas of this?

![](https://camo.githubusercontent.com/c9bae4e4028ebaab6835590cc66fbdb019533e8c/68747470733a2f2f7062732e7477696d672e636f6d2f70726f66696c655f696d616765732f3937393430353235343631323534353533362f5741656330396d6e5f323030783230302e6a7067 )

**Comment by k-syusteem** [comment]
Well, I'll try!

@jorgebucaran, Do you have a discord or something?

**Comment by frenzzy** [comment]
There are a badge [Join us on Slack](https://hyperappjs.herokuapp.com) in [README](https://github.com/hyperapp/hyperapp#readme): [![Slack](https://hyperappjs.herokuapp.com/badge.svg)](https://hyperappjs.herokuapp.com "Join us")

**Comment by Swizz** [comment]
@k-syusteem You can join us on Slack.

[![Slack](https://hyperappjs.herokuapp.com/badge.svg)](https://hyperappjs.herokuapp.com "Join us")

**Comment by k-syusteem** [comment]
Ok, thank you @Swizz and big thank to @frenzzy !

### Cheeers!

**Comment by ThobyV** [comment]
![ha2](https://user-images.githubusercontent.com/26300284/41497219-8623a466-7140-11e8-87c6-adcc9ed9f5c5.png)
![ha3](https://user-images.githubusercontent.com/26300284/41497270-6c082c5e-7141-11e8-96ef-8386e9cf7c0c.png)

Here's my own entry in proposal for the new hyperapp logo. P.s ( I'm a big fan of the old logo too and most of the new logos on this page!)

I was able to base this logo on the following criteria.

• Since Hyperapp follows the Elm architecture, hence the colors.

• Hyperapp promotes pure components, which is why the main logo structure comes from carbon chains components of organic compounds. 😎🙏

Feedback and changes are very much appreciated guys. I'm also making more samples to increase the variations.

Thank you!

**Comment by jorgebucaran** [comment]
@ThobyV That looks amazing!

**Comment by selfup** [comment]
Might I suggest

Purple
Hot Pink
Cyan

Just a thought 😄

**Comment by ThobyV** [comment]
Hello guys, thanks so much for your feedbacks, I managed to *rebrand* the original concepts to these:
![sam le1](https://user-images.githubusercontent.com/26300284/41567278-ea733b56-734e-11e8-8693-359dc0d4bffe.png)
![sample2](https://user-images.githubusercontent.com/26300284/41567291-f79761a4-734e-11e8-8546-15fce6771044.png)

My aim was something fluid, new and components based. I'm still making several iterations and research to see if these can be improved. 

• The first one is based on pure components and hyperapp original color.

• The second is based on suggestions from comments I've read on this issue  (phew! You
guys are awesome 💥).

More feedback and comments are welcome 🙏😎

![haa-3](https://user-images.githubusercontent.com/26300284/41567511-34ec5d74-7350-11e8-85e9-e4545cba3655.png)

**Comment by atomiks** [comment]
Wow I love this one:

![img](https://user-images.githubusercontent.com/26300284/41567291-f79761a4-734e-11e8-8546-15fce6771044.png)

**Comment by ThobyV** [comment]
Thanks @atomiks I'll try out these too. They're cool 😎

**Comment by olstenlarck** [comment]
Heyy! This thread looks awesome :tada: 

But please stop the hexagon trend ;d I liked the droplet style. What about some droplet and 3 cubes in it? As about the text, original suggestions by the author are good.

**Comment by ThobyV** [comment]
True @olstenlarck

Being a designer/developer I've come across so many hexagon logo types, they're trends.😂 

But again, this gives room for more work and research on it because hyperapp is really top stuff and deserves a quality logo.

I'm trying to make something similar to an emoji shape so we can use that alongside hyperapp mentions on twitter. 💫😎😎🤗

**Comment by olstenlarck** [comment]
Yup, definitely good idea. : ))

Don't get me wrong, i'm love hexagons even since before nodejs was born :D

**Comment by TacoTheDank** [comment]
lmao the power glove, I love it

**Comment by border-radius** [comment]
![hyper](https://user-images.githubusercontent.com/3204785/47008715-7cb43900-d143-11e8-8ac9-e07b943ac4e5.png)

**Comment by zaceno** [comment]
@border-radius I'd buy that shirt!

**Comment by jorgebucaran** [comment]
I remembered this and since V2 is now just around the corner, I'm open to ideas again. Here's something I crafted myself.

![1](https://user-images.githubusercontent.com/56996/56082389-4e45bb00-5e53-11e9-96aa-fd2f2d3159f7.png)

**Comment by jorgebucaran** [comment]
Here's one more. What if the logo was not a logotype, but an ideogram/pictogram?

![](https://user-images.githubusercontent.com/56996/56097701-f67e8100-5f32-11e9-8a83-1eb27fe9c6f2.png)

**Comment by okwolf** [comment]
I kinda like the concept of an ideogram/pictogram, but I'm not sure about the specific example that looks a pointer cursor to me.

**Comment by jahoops** [comment]
Just tossing out an idea
[image: image.png]

**Comment by jorgebucaran** [comment]
@jahoops Attachment fail? 😄

**Comment by jorgebucaran** [comment]
![Hyperapp2](https://user-images.githubusercontent.com/56996/56412276-91be8000-62be-11e9-92e4-da589a2a934f.png)

**Comment by frenzzy** [comment]
This is not triple A color combination ([not WCAG 2 AAA Compliant](http://accessible-colors.com/)) 😜

**Comment by jorgebucaran** [comment]
![#0065ff](https://user-images.githubusercontent.com/56996/56432936-2ac6b880-630a-11e9-9016-9eb74ab28e31.png)

@frenzzy Hmm, not bad.

**Comment by okwolf** [comment]
I think I like the new color better. But I'm less sure about the shape :bowtie:

**Comment by jorgebucaran** [comment]
@okwolf You are welcome to submit a proposal.

**Comment by jorgebucaran** [comment]
![Hyperapp](https://user-images.githubusercontent.com/56996/56672305-32fb6b00-66f1-11e9-97c4-18f5dc2dc79e.png)
