### ISSUE TITLE
Add Hyperapp to Custom Elements Everywhere

### ISSUE THREAD

**Issue by Siilwyn** [jorgebucaran/hyperapp#733]
Just a thought, it would be nice to have tests for hyperapp at https://custom-elements-everywhere.com. Related to #702 since having custom web element support would mean there is no need for specific hyperapp components.

**Comment by zaceno** [comment]
I second this!

Although, just to be clear, such tests would only be to make sure custom elements (made with any framework/lib) can work in hyperapp-apps. It’s not about making custom elements using hyperapp (although that shouldn’t be a problem)

I’m pretty sure hyperapp v1.2.6 could pass 100%. Not as certain when it comes to v2 (because of how events are wired)

**Comment by jorgebucaran** [comment]
> @zaceno Not as certain when it comes to v2 (because of how events are wired).

Do you have any idea what tests or what category/area of tests would fail because of how events are wired in V2?

**Comment by zaceno** [comment]
@jorgebucaran Not really, no. I just know that somehow v2 is going to wire events to dispatch, requiring events to be written a certain way (?). And there seems to be a lot of focus on events in those tests.

**Comment by zaceno** [comment]
For instance React doesn’t have 100% because of their internal synthetic event mechanism.

**Comment by jorgebucaran** [comment]
@zaceno Interesting! Behind the scenes, Hyperapp is using addEventListener/removeEventListener so if that works, then it works. I made a [little POC](https://github.com/jorgebucaran/superfine/issues/135#issuecomment-405036380) in Superfine. Please take a look.

**Comment by zaceno** [comment]
@jorgebucaran Yes making custom elements using hyperapp/superfine works great (I’ve tried as well)

But here the question is how well it can work to *use* custom elements (made with other libs/frameworks) in a hyperapp-app.

Again, I’m pretty sure those tests will pass for v1.2.6, less certain in v2 because of the wiring events to dispatch. We’ll have to wait and see.

**Comment by zaceno** [comment]
First of all, someone should open an issue on the custom-elements-everywhere to “claim” the opportunity to write the hyperapp tests (according to their contribution guidelines) 

I’d do it but I’m quite busy at the moment. If no one else has started on it by the time things settle down, I’ll look into it.

**Comment by jorgebucaran** [comment]
According to the [Custom Elements Everywhere](https://github.com/webcomponents/custom-elements-everywhere) documentation:

> **Why don't you have tests for _____ library?**
...if a framework or library is not represented it's just because we haven't had a chance to write tests for it yet.

> **I want to write some tests for _____ library. Do you accept pull requests?**
_Yes_! In fact, >50% of the tests on this site are from external contributors.

If anyone wants to give this is a shot, please do! I may eventually do it myself, but it isn't my top priority at the moment so I can't make any promises. I do want Hyperapp on that list, though. If you want to help, this is a way to contribute back! 💯

**Comment by Swizz** [comment]
Not claimed yet. But as I am working on Custom Elements lately, I gave a try to this.

Here a sneaky peak of the results. For hyperapp@beta. 

![Hyperapp results on Custom Elements Everywhere](https://snag.gy/hrzpUs.jpg)

Like @zaceno said : is all about how Hyperapp v2 handle events.

(Pushed on my repo fork but, I will wait Hyperapp to leave the beta stage, to make a PR on the Custom Elements Everywhere repository.)
