### ISSUE TITLE
Hyperapp on Best of JavaScript / Move from hyperapp org

### ISSUE THREAD

**Issue by michaelrambeau** [jorgebucaran/hyperapp#759]
Hello Jorge @jorgebucaran ,
Thank you for your amazing work.

I run a project called _Best of JavaScript_ where you can see that _HyperApp_ is the 4th trendiest UI framework, taking into account the GitHub stars over the last 12 months: https://bestofjs.org/tags/framework/trending/last-12-months

![image](https://user-images.githubusercontent.com/5546996/45583751-78a5b900-b902-11e8-9b81-a5fd08528d6a.png)

I wonder if there is a reason why the project moved from https://github.com/hyperapp to your personal account?

I'm asking because the org icon used to be displayed as the project icon but now it's your avatar that shows up.

If the repo is going to stay on your account, I will set up manually the right icon for the project.
(and it's not because I don't like your avatar 😄 !)

![image](https://user-images.githubusercontent.com/5546996/45583775-dcc87d00-b902-11e8-93f4-9d6b070bb98f.png)

Thank you for your answer!
By the way `superfine` is also on _Best of JavaScript_, keep up the great work!

**Comment by jorgebucaran** [comment]
> @michaelrambeau If the repo is going to stay on your account, I will set up manually the right icon for the project.

Hi Michael! Yes, and I'd also like to you ask you to use the following icon instead:

<samp>https://avatars3.githubusercontent.com/u/36233926</samp>

![](https://avatars3.githubusercontent.com/u/36233926)

> I wonder if there is a reason why the project moved from https://github.com/hyperapp to your personal account?

I decided to put it back under my account. The <github.com/hyperapp> organization will be used to host related repositories like awesome-hyperapp, CLI tools, migration tools, or projects of collective interest such as real world examples: RealWorldApp, TodoMVC, etc. 

> By the way superfine is also on Best of JavaScript, keep up the great work!

I just found it: https://bestof.js.org/projects/superfine 😍 

Thanks for letting me know. I noticed the npm package name was not correct. Could you change it to <samp>superfine</samp> please?

---

There is a possibility the logo might change again in the future (see #694), if that happens I'll post a message in this thread so that you are notified.

Cheers! 🙌

**Comment by jorgebucaran** [comment]
> @michaelrambeau Also I fixed the package name for superfine package, it seems that package had several lives (it used to be called PicoDOM, PatchDOM and UltraDOM according to my personal notes!)

Oh, yes, I know. We all know. 🤣 

> And you live in Japan, too, we may meet one day to talk about JavaScript, who knows.

Yes, in Tokyo. I should definitely visit Osaka one of these days.

**Comment by jorgebucaran** [comment]
> Best of JavaScript has been updated with the right icon.

Thank you! 🙌:tada:

**Comment by jorgebucaran** [comment]
@michaelrambeau It seems the logo is out of sync again. I'm getting a broken image. 💔 

One more thing, it seems Hyperapp is listed as a UI framework, but not as a Virtual DOM. This seems inconsistent because Hyperapp is also a Virtual DOM. Would it be possible to add the **Virtual DOM** label (in addition to **UI Framework**) to Hyperapp?

**Comment by jorgebucaran** [comment]
Yo~! @michaelrambeau It seems the logo is out of sync again. I'm getting a broken image. 💔 

One more thing, it seems Hyperapp is listed as a UI framework, but not as a Virtual DOM. This seems inconsistent because Hyperapp is also a Virtual DOM. Would it be possible to add the **Virtual DOM** label (in addition to **UI Framework**) to Hyperapp?
