### ISSUE TITLE
Typeahead PoC

### ISSUE THREAD

**Issue by mshgh** [jorgebucaran/hyperapp#845]
With **ha2** reaching beta I decided to build PoC of typeahead component to see how this would work.
Here are my two key requirements
- this has to be easily reusable component
- to not store suggested values in the state

Here is [the PoC](https://rawcdn.githack.com/mshgh/ha2-samples/typeahead-v3/index.html)

I would like to ask
- is the way I work with effects correct? [oninput() method](https://github.com/mshgh/ha2-samples/blob/typeahead/lib/components.js#L22) and its [usage](https://github.com/mshgh/ha2-samples/blob/typeahead/lib/components.js#L56)
- what would be the best way to make http api mockable for local development?

**Comment by jorgebucaran** [comment]
1. It's not _wrong_ because you figured out to make it work, but I wouldn't say it's correct or even remotely close to ideal. For effects, use an existing effect library or create a generic one, then write actions to use it. What I see is a specific effect implemented inside the oninput event handler. 
2. I might be misunderstanding the question, so let me know if you think I did. When working with effects, you don't need to mock any APIs ever! :)

**Comment by mshgh** [comment]
Actually when I got to the point I should use `@hyperapp/http` I found out this was not ready yet. So I decided to write my own custom effect ;) I have no problem to wait for this effects library to be ready and see what it does to the PoC.

I see I should have asked my mock-question differently. Not based on assumption I need to mock the http API. As I expect the implementation will be different enough with usage of the effects library let me park this question till I have the final solution ready.

**Comment by jorgebucaran** [comment]
Whoa, it's really been a while, isn't it? I don't know if we still have an issue here, but it looks like there's nothing actionable here so I'm closing. FYI I'm currently working on `@hyperapp/http`, which ~~I hope~~ should become the recommended way to talk with servers back and forth with Hyperapp in a way that makes sense to Hyperapp. ✨💫
