### ISSUE TITLE
Subscription is restarted when in a dynamic array

### ISSUE THREAD

**Issue by mrozbarry** [jorgebucaran/hyperapp#859]
If I have a state `{ subscriptionsIteratesOverThis: [] }`, which gets items added and removed, it can force some subs to be restarted if I map over `state.subscriptionsIteratesOverThis` to generate subs.

I'm not sure if this is a bug or just something that developers need to be aware of when calling subscriptions.

For example, related to the code I posted in #857 , I have a countdown where I pass it the time when the countdown should be done, and it dispatches progress actions periodically, represented by the percentage of time between when the subscription was started and the target done time. The problem is if the start time was 100, and end time 200, and we hit 150, that's 50%. When the sub restarts, the start time becomes 150, and changes the completed percentage on the next progress action.

The easy solution on my side is to make sure the subscription gets a reference of the start time rather than track that in a local state, then it will always know the appropriate percentage, and maybe that's the correct solution.

I guess this demonstrates that we may get _unnecessary_ subscription restarts, but I'm not convinced this is a bug.

**Comment by jorgebucaran** [comment]
@mrozbarry The countdown logic could be refactored so you don't need to call `tick` right away.

**Comment by mrozbarry** [comment]
@jorgebucaran this one isn't about the infinite loop. This has to do with subscription restarts when array indexes change.

As I state at the bottom, too, I'm not convinced if this is a bug, or just something that needs to be documented.

**Comment by jorgebucaran** [comment]
@mrozbarry Could you make a small repro?

**Comment by mrozbarry** [comment]
@jorgebucaran Yeah, I'll toss a codepen up tonight (about 5 hours, give or take)

**Comment by mrozbarry** [comment]
@jorgebucaran https://codepen.io/mrozbarry/pen/VJGjOo?editors=0010
Sorry for the delay!

**Comment by mrozbarry** [comment]
This also accidentally highlights another issue with subs being re-started constantly, which isn't the bug, but is a problem non-the-less.

**Comment by jorgebucaran** [comment]
@mrozbarry This is because we use order/index to identify a subscription, much in the same way we use keys in the VDOM to identify elements. Looking for a _key_ (not props as that would be slow as hell) in your props to identify the subscription could work, though. Keyed VDOM, keyed subscriptions. Interesting.

**Comment by sergey-shpak** [comment]
@jorgebucaran we have already touched this issue at Slack channel, but I'll raise it once more, because it's related to subscriptions and not so obvious

Passing array as property (even with the same values) to subscription can create subscription re-initialization on each state change
```javascript
app({
  subscriptions: state =>
    [effect, { action, some: [ 'param' ] }],
})
```
*example, https://codepen.io/sergey-shpak/pen/MMqBRO

It is related to internal subscriptions patching(shallow compare) algorithm, 
and can be easily solved with passing array reference instead of creating array 
```javascript
const some = [ 'param' ]
app({
  subscriptions: state =>
    [effect, { action, some }],
})
```
It's not so critical but it should be known and mentioned/explained at the docs

**Comment by mrozbarry** [comment]
@sergey-shpak my issue had nothing to do with array subscription props.

**Comment by jorgebucaran** [comment]
@sergey-shpak Yes, that should come as no surprise to anyone. 😄

**Comment by sergey-shpak** [comment]
@mrozbarry you're 100% right, just decided to mention in case anyone got the same issue :eyes:

**Comment by sergey-shpak** [comment]
@mrozbarry Unless hyperapp implements 'keyed' subscriptions this can be workarounded with storing additional array map for dynamic arrays:

```javascript
const state = {
  array: [],
  // you have to create array map specially for subscriptions
  arrayMap: []
}

// and now whenever you need to update array (dynamically)
// you have to also properly update arrayMap, something like:

const addItem = (state, item) => ({
  array: state.array.concat(item),
  arrayMap: state.arrayMap.concat({ enabled: true, item })
})

const updateItem = (state, item) => ({
  array: state.array.map(i => i.key === item.key ? item : i),
  arrayMap: state.arrayMap.map(i => 
    i.item.key === item.key ? { enabled: true, item } : i
  )
})

const removeItem = (state, item) => ({
  array: state.array.filter(i => i.key !== item.key),
  arrayMap: state.arrayMap.map(i => 
    i.item.key === item.key ? { enabled: false, item: null } : i
  )
})

app({
  init: state,
  subscriptions: state => [
    // since subscriptions are now based on arrayMap and 'enabled' flag
    // subscriptions are (re)initialized only for changed/edited/appended/removed items 
    arrayMap.map(item => 
      item.enabled && [Subscription, item.item]
    )
  ]
})
```
after some thoughts I've came that storing data as array is not quite good idea in general, unless you don't have any other option

Since it's not a common problem - workaround with 'arrayMap' should be ok to solve the issue in dev userland, @jorgebucaran

**Comment by zaceno** [comment]
In principe, stopping and restarting a subscription should work. So restarting more often than intended isn't really a problem except when it comes to be too much.  

For now, there is no apparent use case where this causes real problems (it's just surprising to the developer that the subscriptions are updated), so I think we can close it.

There may come a day when we have concrete use case and need to consider something like a keyed subscriptions structure. We can reopen/refer to this issue then.

**Comment by mrozbarry** [comment]
We should definitely nuke this issue, it's quite old, and it sort of went off the rails a bit anyway.

**Comment by jorgebucaran** [comment]
We can always revisit this later if something comes up. 🙆‍♂️
