### ISSUE TITLE
Example for custom elements

### ISSUE THREAD

**Issue by kethan** [jorgebucaran/hyperapp#871]
Hi,
Can anyone provide me a simple example for creating an custom element with properties and event listener. Thanks

**Comment by sergey-shpak** [comment]
If I remember right @zaceno was working on custom elements with hyperapp#2

**Comment by jorgebucaran** [comment]
Hyperapp supports [extending native elements](https://developers.google.com/web/fundamentals/web-components/customelements#extendhtml), but browser support is so-so:

> [Try on CodePen](https://codepen.io/jorgebucaran/pen/pMxNdE?editors=0010)

```js
import { MDCRipple } from "@material/ripple"

customElements.define(
  "ripple-button",
  class extends HTMLButtonElement {
    constructor() {
      super()
      this.className = "mdc-button mdc-button--raised"
      MDCRipple.attachTo(this)
    }
  },
  { extends: "button" }
)

import { h, app } from "hyperapp"

app({
  init: 0,
  view: state =>
    h("main", {}, [
      h("h1", { class: "mdc-typography--headline1" }, state),
      Array.from({ length: (state % 3) + 1 }).map(() =>
        h("button", { is: "ripple-button", onclick: state => state + 1 }, "+")
      )
    ]),
  node: document.getElementById("app")
})
```

**Comment by jorgebucaran** [comment]
[Here's an example](https://codepen.io/jorgebucaran/pen/BXqQwB?editors=1010) without `extends` that will work in more browsers.

```js
/* MDCRipple interface */
import { MDCRipple } from "@material/ripple"

const fx = a => b => [a, b]
const ripple = fx((_, list) =>
  requestAnimationFrame(() => Array.from(list).map(MDCRipple.attachTo))
)
```
```js
/* Custom Element */
customElements.define(
  "ripple-button",
  class extends HTMLElement {
    constructor() {
      super()
    }
    connectedCallback() {
      app({
        init: [this.textContent, ripple(this.childNodes)],
        view: state =>
          h(
            "button",
            { id: "x", class: "mdc-button mdc-button--raised" },
            state
          ),
        node: this.childNodes[0]
      })
    }
  }
)
```

```js
import { h, app } from "hyperapp"

app({
  init: 0,
  view: state =>
    h("main", {}, [
      h("h1", { class: "mdc-typography--headline1" }, state),
      Array.from({ length: (state % 3) + 1 }).map(() =>
        h("ripple-button", { onclick: state => state + 1 }, "+")
      )
    ]),
  node: document.getElementById("app")
})
```

**Comment by jorgebucaran** [comment]
@kethan See my two examples above. Now you know how to use Hyperapp with custom elements. You can implement your custom elements with or without Hyperapp. I showed you how to do it with Hyperapp. If you're not using Hyperapp to implement custom elements, I can recommend [Superfine](https://github.com/jorgebucaran/superfine). It doesn't matter how you implement your custom elements, they'll work with any framework.

**Comment by kethan** [comment]
unable to refer node without ripple button.

`customElements.define(
        "hello-world",
        class extends HTMLElement {
            constructor() {
                super()
            }
            connectedCallback() {
                //             this.innerHTML = `
                //   <p>Hello From Web Component</p>
                // `;
                app({
                    init: 0,
                    view: state => html`<b>hello<${state}/b> `,
                    node: this.childNodes[0]
                })
            }
        }
    )`

**Comment by zaceno** [comment]
@kethan Could you put that in a codepen - or rather, put what you expect to work but doesn’t in a codepen (and explain in a comment what you want to happen). Might be able to help but I’m not sure what you’re asking.

**Comment by kethan** [comment]
Can I have just an example with ripple button because I don't know what to attach in node.

**Comment by kethan** [comment]
https://codepen.io/kethan-the-selector/pen/XWrmMZP?editors=1010

**Comment by jorgebucaran** [comment]
@kethan No ripple button. https://jsfiddle.net/ayqs4gub

```html
<div id="app"></div>
```
```js
import { h, app } from "hyperapp"

customElements.define(
  "hello-world",
  class extends HTMLElement {
    connectedCallback() {
      app({
        init: this.textContent,
        view: state => h("h1", {}, `Hello, ${state}`),
        node: this.childNodes[0]
      })
    }
  }
)

app({
  init: "Hyperapp",
  view: state => h("div", {}, [h("hello-world", {}, state)]),
  node: document.getElementById("app")
})
```

**Comment by zaceno** [comment]
@jorgebucaran @kethan 

I'm not sure how it's possible to use `this.childNodes[0]` for the `node` property. It doesn't make sense to me. 

But anyhow, I'd recommend using shadow-dom. In the past there have been interference between custom elements and outer Hyperapp's that render them.

For capturing child-content passed to the custom element, I would use the "slots" api:

https://codepen.io/zaceno/pen/gOYaQWB?editors=1010

**Comment by jorgebucaran** [comment]
Or extend native elements like I did [here](https://github.com/jorgebucaran/hyperapp/issues/871#issuecomment-520139012); it's more powerful.

**Comment by zaceno** [comment]
I checked and it appears that as long as you let your custom-elements control their own children, it's safe to use "light-DOM": 

https://codepen.io/zaceno/pen/wvwMoQj?editors=0010

(@kethan that example also has a custom element dispatching an event which you asked about earlier)

But of course, if you want a custom element that is like some sort of container for content rendered into it from the outside, you will still need to use shadow dom (hyperapp cannot handle rendering inside custom-elements if the custom-elements are modifying their own children also.)

**Comment by kethan** [comment]
@zaceno @jorgebucaran  Thanks for your efforts slowly I have started to understand how hyperapp works.

**Comment by kethan** [comment]
Hi,
I tried this example. https://codepen.io/kethan-the-selector/pen/XWrmMZP?editors=1010
 In that, I am manually updating the attribute that is linked to the state but the count in view is not updated.

```js
   setTimeout(() => {
        this.setAttribute('count', '100')
    }, 3000)
```

**Comment by zaceno** [comment]
@kethan 

First, there is something important to understand about `state`: every time you dispatch an action (like for `onClick` in your counter buttons), you should return a **new** object containing the entire new state. If you don't, Hyperapp will not rerender your app, because it can't tell that the state is different.

That means, every time something changes, the state-object that hyperapp is managing is a new object. Changing something in the _initial_ state object does nothing (like you are doing in `this.state.count = ...`), because Hyperapp has long since forgotten about it.

What you need to do instead, is to get an action dispatched which can set the new count value. That action should look like:

```
(state, newCountValue) => ({...state, count: newCountValue})
```

You already know how to dispatch actions in response to DOM events – you express them as for instance `onClick` properties in the view. But what about other kinds of events, such as timer-intervals, global keyboard events, or when an attribute changes? For everything *except* DOM events, you should use *subscriptions* 

Hyperapp doesn't yet offer a way to subscribe to attribute changes in custom elements. That means you will need to implement your own subscription for this. Once you understand how subscriptions work, it's not really that difficult, or even very much code. Unfortunately the docs aren't ready yet, and even if they were this would be considered "advanced level".

So the best I can do to help, I think, is to provide this working example of what you were trying to do, and offer to answer any questions about it you might have, as best I can:

https://codepen.io/zaceno/pen/eYOZzGm?editors=1010

Notice the `Subscribable` thing I added to it. What it does is: it instantiates a container for holding a value (with set/get). Note the `onset` method: that is a *subscription* which is added to the `app`s `subscriptions:` property, referring to `SetCount`, so that any time someone calls `this.appvars.count.set(42)`, then the `SetCount` action will be dispatched, with the current state as first argument and 42 as the second argument.

Sorry for the long-winded explanation. I guess you'll just have to accept you jumped in the deep end trying to implement custom elements with hyperapp ;) Anyway, hope it helped!

**Comment by kethan** [comment]
> Hyperapp doesn't yet offer a way to subscribe to attribute changes in custom elements. That means you will need to implement your own subscription for this. Once you understand how subscriptions work, it's not really that difficult, or even very much code. Unfortunately the docs aren't ready yet, and even if they were this would be considered "advanced level".

Oh wow! that really looks overdose to me. lol. Glad. I will take the time to understand first how subscription works. But you have done an awesome job to explain thanks.
