### ISSUE TITLE
Logger middleware, middleware composer, and router

### ISSUE THREAD

**Issue by chrisdavies** [jorgebucaran/hyperapp#918]
I put together a few tools to help with my current hyperapp project.

[hypermiddleware](https://github.com/chrisdavies/hypermiddleware) is a middleware logger similar to redux-logger, and a middleware composer (allowing you to write N middleware functions, and then easily compose them into a single middleware function).

[hyperoute](https://github.com/chrisdavies/hyperoute) is a router.

If you'd like to incorporate any of these into the core libs, I'm happy to open PRs for that, and then maintain these moving forward. Otherwise, feel free to close this issue!

Thanks for hyperapp!

**Comment by frenzzy** [comment]
Maybe create a PR to https://github.com/jorgebucaran/awesome-hyperapp ?

**Comment by sergey-shpak** [comment]
Because of hyperapp minimalistic design almost every hyperapp developer writes something similar - here is my [hyperapp-middlewares](https://github.com/sergey-shpak/hyperapp-middlewares) package and [router](https://github.com/jorgebucaran/hyperapp-router/pull/100) :), imo, even though there are many different packages from developers, they shouldn't be pushed into the core - hyperapp core should stay as it is without any additional functionality

**Comment by zaceno** [comment]
@frenzzy props for reminding us about awesome-hyperapp. That really needs a complete refresh or a big fat disclaimer though. All of it as far as I can tell is v1 related. 

Should we start a new one? Or is that what the upcoming “ecosystem” page on the website is for @jorgebucaran?

**Comment by jorgebucaran** [comment]
> Should we start a new one? Or is that what the upcoming “ecosystem” page on the website is for @jorgebucaran?

I think a PR to awesome-hyperapp is better than nothing for now! 💯 

Thank you, @chrisdavies!

**Comment by chrisdavies** [comment]
Will do... after I tidy up the packages a bit more!
