### ISSUE TITLE
Two interval subscriptions, but only one fires

### ISSUE THREAD

**Issue by anticrisis** [jorgebucaran/hyperapp#930]
Are two intervals supposed to work?

```js
import { h, app } from 'hyperapp'
import { interval } from '@hyperapp/time'

app({
  init: { t1: 0, t2: 0 },
  view: (s) =>
    h("div", {}, [
      h("p", {}, `Time 1: ${s.t1}`),
      h("p", {}, `Time 2: ${s.t2}`)
    ])
  ,
  subscriptions: (s) => [
    interval((s, d) =>
      ({ ...s, t1: d }), { delay: 1000 }),

    interval((s, d) =>
      ({ ...s, t2: d }), { delay: 3000 }),

  ],
  node: document.getElementById("app")
})
```
**Expected result**: both time markers increment periodically.

**Actual result**: only the time increment associated with the lower delay value increments. The other remains at "0".

Whichever timer delay is lower is the one that fires. Test by swapping the delay values between the two. Seen on Firefox and Edge.

**Comment by zaceno** [comment]
@anticrisis 

The problem is, you are inlining the actions in the subscriptions. That way, everytime the subscription list updates, it looks like you are defining a new subscription, so the previous subscriptions are stopped and new ones are started. That's why the longer-delayed one never gets a chance to fire.

It's a really common mistake, and as we improve the docs I'm sure we'll make it very clear that inlining actions is a no-no.

What you need to do is simply define the actions as static constants, and refer to them in the interval calls

```js
import { h, app } from 'hyperapp'
import { interval } from '@hyperapp/time'

const T1Tick = (s, d) => ({ ...s, t1: d })
const T2Tick = (s, d) => ({ ...s, t2: d })

app({
  init: { t1: 0, t2: 0 },
  view: (s) =>
    h("div", {}, [
      h("p", {}, `Time 1: ${s.t1}`),
      h("p", {}, `Time 2: ${s.t2}`)
    ])
  ,
  subscriptions: (s) => [
    interval(T1Tick, { delay: 1000 }),

    interval(T2Tick, { delay: 3000 }),

  ],
  node: document.getElementById("app")
})
```

**Comment by anticrisis** [comment]
Oh! Excellent, that makes a lot sense. Thank you!
