### ISSUE TITLE
Restarted subs run new before unsubscribe

### ISSUE THREAD

**Issue by okwolf** [jorgebucaran/hyperapp#944]
I ran into an unexpected behavior when a subscription restarts where the subscription function is called with the new props _before_ the old subscription cleanup/unsubscribe function is run. This order can cause issues if the setup/teardown of the subscription operates on a shared resource where running the cleanup after subscribing breaks things.

Here's the line of code causing the behavior: https://github.com/jorgebucaran/hyperapp/blob/4121de9db41a3e98d8407b00b2a26f0eb410d96d/src/index.js#L85

I would have expected the line after to execute first:
https://github.com/jorgebucaran/hyperapp/blob/4121de9db41a3e98d8407b00b2a26f0eb410d96d/src/index.js#L86

Is this intentional/expected?

**Comment by jorgebucaran** [comment]
@okwolf Can you provide a demo? We can't do much here without one.

**Comment by okwolf** [comment]
@jorgebucaran sure, here's a fairly minimal one: https://codepen.io/okwolf/pen/oNjwjBN?editors=0011

And the order events happen in:
![subs-order](https://user-images.githubusercontent.com/3735164/80409251-5f564400-887d-11ea-8ef4-7ffbad860f63.PNG)

- First sub starts
- Sub prop changes
- Sub two starts
- Sub one stops

**Comment by infinnie** [comment]
https://github.com/jorgebucaran/hyperapp/blob/4121de9db41a3e98d8407b00b2a26f0eb410d96d/src/index.js#L85-L86

It appears clearer that the new subscription would be executed _before_ the old one.

**Comment by shish** [comment]
Extra context: managing websockets with hyperapp-fx, trying to make auto-reconnect work. hyperapp-fx caches websockets by URL (so if you have one websocket subscription and multiple websocket actions, they all use one socket under the hood).

My understanding: There was a suggestion that we could implement auto-reconnect by having an `error_count` prop which would be incremented on each error, and then hyperapp would see "the props have changed, time to replace the subscriber" - but if "replace" does "add" first and "remove" second, then the reference count for the underlying websocket in the cache never reaches zero - so it never goes away, and our new subscriber ends up recycling the old (broken) socket instead of creating a new one.

**Comment by okwolf** [comment]
This issue can be revisited once Hyperapp supports restarting subs again, hopefully in #992. 🙏 

Once that happens I'll make a PR, should be only +2 bytes.

**Comment by jorgebucaran** [comment]
Can we revisit this now? #992 was just merged and published. 🙏

**Comment by okwolf** [comment]
Thanks for the merge and release! First I've updated [my pen to repro the problem](https://codepen.io/okwolf/pen/oNjwjBN?editors=0011) with the latest version, about to make a PR for my proposed fix.
