### ISSUE TITLE
Cannot render virtual node with hyperapp

### ISSUE THREAD

**Issue by winston0410** [jorgebucaran/hyperapp#971]
I am new to hyperapp, and I am trying to use it in my open source project. I read the doc, and it seems like Hyperapp can be easily set up, but I cannot render the virtual node to the target DOM element. Did I missed anything here?

`console.log()` for my DOM element, with its child being the virtual node generated with Hyperapp

```js
HTMLDivElement {
  [Symbol(SameObject caches)]: [Object: null prototype] {
    classList: DOMTokenList {},
    dataset: DOMStringMap {},
    childNodes: NodeList {}
  }
}
```

My code:

```js
const blockContainer = document.createElement("div")
blockContainer.classList.add(
  "freedom-editor-blocks",
  `${this.constructor.name}-block`
)
blockContainer.dataset.blockType = this.constructor.name

app({
  init: {
    i18n: i18n,
    savedData: savedData,
  },
  node: blockContainer,
  view: ({ i18n, savedData }) => {
    return (
      <pre>
        <code contenteditable>{getSavedData(savedData)}</code>
      </pre>
    )
  },
})
```

I haven't tried hyperapp in browser yet, do I need more packages if I am going to test it with Jasmine and jsdom in Node.js?

**Comment by zaceno** [comment]
@winston0410 I suspect it's your use of JSX that is the problem.  The log output you showed made it look like the jsx is not being turned into proper hyperapp vnodes. Maybe React vnodes?  You need to set the proper "pragma" in your babel settings for the jsx plugin, in order to translate jsx into hyperapp vnodes.

In olden times (a couple of weeks ago) you could set the pragma to `"h"` and `import {h} from 'hyperapp'` in all files that use jsx. 

Since version 2.0.5 (current is 2.0.8) that does not work anymore. You need to add a small function to your project like this: 

'hyperapp-jsx.js':

```js
import {h, text} from 'hyperapp'

export default (type, props, ...children) =>
  typeof type === "function"
    ? type(props, children)
    : h(
        type,
        props || {},
        []
          .concat(...children)
          .map((any) =>
            typeof any === "string" || typeof any === "number" ? text(any) : any
          )
      )
```

And then `import h from 'hyperapp-jsx.js'`

As for testing in node you shouldn't need any other packages. Should be fine as your project is an es-module ("type": "module" in your package.json)

**Comment by jorgebucaran** [comment]
@winston0410 Hyperapp is not compatible with JSX "out of the box". But that doesn't mean you can't use JSX, as @zaceno said, it's possible to wrap Hyperapp's hyperscript function to take care of it.

[Here's a pen](https://codepen.io/jorgebucaran/pen/QWyPeGv) that shows how to do it.

> ...do I need more packages if I am going to test it with Jasmine and jsdom in Node.js?

I don't know if Jasmine supports ES modules by default, but if it does, then the answer is no, you can test your views using JSDOM, Node.js and your test runner—good luck! 👋

**Comment by winston0410** [comment]
> ```js
> import h from './hyperapp-jsx.js'
> ```

Awesome!  Used this and everything works well.  This should be added to the doc. 

By the way, why would this not be shipped as default in Hyperapp?  I guess it won't add much weight to whole file.

**Comment by winston0410** [comment]
> @winston0410 Hyperapp is not compatible with JSX "out of the box". But that doesn't mean you can't use JSX, as @zaceno said, it's possible to wrap Hyperapp's hyperscript function to take care of it.
> 
> [Here's a pen](https://codepen.io/jorgebucaran/pen/QWyPeGv) that shows how to do it.
> 
> > ...do I need more packages if I am going to test it with Jasmine and jsdom in Node.js?
> 
> I don't know if Jasmine supports ES modules by default, but if it does, then the answer is no, you can test your views just with JSDOM, Node.js and Jasmine (or any test runner).
> 
> Keep us posted and good luck! 👋

I am not sure if I can understand this pen correctly. The `jsx` function is defined but never called, then how would it help transform jsx syntax?

Anyway, I really like how compact Hyperapp is, and especially the naming of parts like view, init, action, and subscription in Hyperapp.  It really helps a beginner like me to understand MVVM.  Awesome work!

**Comment by zaceno** [comment]
@winston0410 

> I am not sure if I can understand this pen correctly. The jsx function is defined but never called, then how would it help transform jsx syntax?

Notice this comment:
```
 /** @jsx jsx */
```
– it's a secret trick to tell codepen what pragma to use for jsx transform. 😉 

> This should be added to the doc.

Don't expect too much from any docs at the moment since hyperapp v2 is not yet "officially" launched the docs are still under development. But when it is officially launched I would expect this sort of hint to be available somewhere for sure!

> By the way, why would this not be shipped as default in Hyperapp? I guess it won't add much weight to whole file.

@jorgebucaran would have to answer for how he made the choice (it was built in before), but the pros to dropping JSX support is that you can get faster performance as well as smaller bundle size, if you don't use JSX at all (write your views using plain `h` and `text` calls) – so I think a fair chunk of people will prefer to go that approach, and the ones who want to use JSX (or my own https://github.com/zaceno/hyperlit) they still can with just a smidge of extra effort.

**Comment by jorgebucaran** [comment]
@winston0410 That's the JSX pragma: `/** @jsx foobar */`, which is a compiler instruction (directive) that tells Babel: hey use this function here instead of `React.createElement` when compiling JSX to real JavaScript. You can name the function whatever you want, I just went with `jsx`. 

> By the way, why would this not be shipped as default in Hyperapp? I guess it won't add much weight to whole file.

It used to be like that for a long time, but I don't want to rely on a technology that exists essentially to suit React and its idiosyncrasies (e.g. Fragments) and will likely evolve to accommodate future changes in React as well. We (the community) can live without JSX and there's nothing JSX can do we can't do with just JavaScript and in less code. JSX is not JavaScript.

Better size and memory performance was another reason to get rid of the "built-in" JSX support implementation we had. You'll be surprised how trivial it is to go from JSX to `h` or [`@hyperapp/html`](https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html). Give it a chance!

**Comment by winston0410** [comment]
Your explanation is very clear.  Thank you!
