### ISSUE TITLE
Weird behaviour using the basic example

### ISSUE THREAD

**Issue by eezoo** [jorgebucaran/hyperapp#977]
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module">
      import { h, text, app } from "https://unpkg.com/hyperapp"

      const AddTodo = (state) => ({
        ...state,
        todos: state.todos.concat(state.value),
      })

      const NewValue = (state, event) => ({
        ...state,
        value: event.target.value,
      })

      app({
        init: { todos: [], value: "" },
        view: ({ todos, value }) =>
          h("main", {}, [
            h("input", { type: "text", oninput: NewValue, value }),
            h("button", { onclick: AddTodo }, text("Add")),
            h("ul", {},
              todos.reverse().map((todo) => h("li", {}, text(todo)))
            ),
          ]),
        node: document.getElementById("app"),
      })
    </script>
  </head>
  <body>
    <main id="app"></main>
  </body>
</html>
```

I just added `.reverse()` to the UL map function.
Then i added items to the list, `123`, `1234`, `12345`.
The sorting changes while i type... why is that?

**Comment by mshgh** [comment]
This is as the `reverse()` function changes order in-place. see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse => every time the app is rendered you flip the order.
More over you **mutate** your state - do not do this **ever** ;)

Not sure what you want to achieve. Probably easiest is to make a copy and reverse it `[...todos].reverse()`, still reversing the array every time it is rendered seems unnecessary overhead.

**Comment by eezoo** [comment]
I understand, but why re-render occurs on the list while typing?

**Comment by jorgebucaran** [comment]
> @eezoo I understand, but why re-render occurs on the list while typing?

Because you are **mutating** the state. Whenever you change the input value, the view function will be called, and the `todos` array mutated. If you use `[...todos].reverse()` or `todos.slice().reverse()` this won't happen.

Method concatenation like that is a bit ugly IMO, so I suggest you create your own `reverse` function, where you can use an efficient [swap algorithm](https://en.wikipedia.org/wiki/Swap_(computer_programming)#Swap_methods) (or just go with native methods, whatever is faster in JavaScript) and then use it like:


```js
import { reverse } from "./utils.js"

// ...
reverse(todos).map((todo) => h("li", {}, text(todo)))
```
