### ISSUE TITLE
Cannot read property X of undefined

### ISSUE THREAD

**Issue by VictorWinberg** [jorgebucaran/hyperapp#983]
Tutorial with newest hyperapp version gives: `Cannot read property 'is' of undefined`

E.g. https://codesandbox.io/s/hyperapp-tutorial-step-2-forked-k0bmx

This is due to that the `props` parameter to `h` function can be `null`.

**Comment by jorgebucaran** [comment]
@VictorWinberg The tutorial needs fixing, so this is actually not a bug in Hyperapp, just the way it is. Your PR is still worth merging, though. I don't know, you often need a props object. This is not a problem when using JSX, since you'd need to write your own (or import an official one if available) JSX function anyway, that should take care of it.
